name: Detekt

on:
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 11

      - name: Run Detekt
        id: detekt
        continue-on-error: true
        run: ./gradlew detekt

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: app/build/reports/detekt/detekt.sarif

      - name: Fail if Detekt found issues
        if: steps.detekt.outcome == 'failure'
        run: exit 1

